[profile.bench]
debug = true

[workspace]
default-members = ["core"]
version = "0.1.0"
members = [
  "core",
  "bin/bst"
]

[workspace.package]
authors = ["dashjwz@gmail.com"]
edition = "2021"
repository = "https://github.com/dashjay/bytestack"
rust-version = "1.65"
version = "0.1.0"