[package]
name = "bytestack"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
rand = "0.8"
crc = "3.0.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
futures = "0.3"
opendal = "0.37"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }