version: "3"
services:
  # controller:
  #   image: bytestack/controller
  #   restart: unless-stopped
  #   command:
  #     - /controller
  #     - --mongo-uri=mongodb://mongo:27017/?replicaSet=rs0
  #     - --log-level="debug"
  #     - --bind=0.0.0.0:8080
  #   ports:
  #     - 8080:8080
  mongo:
    image: mongo:4.2.3
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    command:
      - mongod
      - --dbpath
      - /data/db
      - --replSet
      - rs0
    ports:
      - 27017:27017
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    volumes:
      - minio-data:/data
    command:
      - minio
      - server
      - /data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - 9000:9000
volumes:
  mongo-data:
  minio-data:
