[package]
name = "turbo"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "turbo"
path = "src/bin/turbo.rs"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
proto = { workspace = true }
