[package]
categories = ["filesystem"]
description = "Bytestack CLI"
keywords = ["storage", "haystack", "s3", "fs"]
name = "bst"
edition.workspace = true
version.workspace = true

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
bytestack.workspace = true
clap = { version = "4.3.10", features = ["derive"] }
log = "0.4.19"
toml = "0.7.5"
